apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: scheduler
  name: spoofed-scheduler
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: scheduler
  replicas: 1
  template:
    metadata:
      labels:
        component: scheduler
    spec:
      containers:
      - command:
        - /kube-scheduler
        - --config=/etc/kubernetes/scheduler-config.yaml
        image: spoofed-scheduler:internal
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10259
            scheme: HTTPS
          initialDelaySeconds: 15
        name: scheduler-plugins-scheduler
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10259
            scheme: HTTPS
        securityContext:
          privileged: false
        volumeMounts:
        - name: scheduler-config
          mountPath: /etc/kubernetes
          readOnly: true
      hostNetwork: false
      hostPID: false
      serviceAccountName: spoofed-scheduler
      volumes:
      - name: scheduler-config
        configMap:
          name: scheduler-config