apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: spoofed-pod-mutation
webhooks:
  - name: pod-mutation.webhook.svc
    clientConfig:
      service:
        name: spoofed-webhook
        namespace: webhook
        path: "/mutate/pods"
      caBundle: "<<CA_BUNDLE>>"
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Ignore
    sideEffects: None
    admissionReviewVersions: ["v1"]